//! Fixtures and comparisons shared by the tone-based decoder's tests.

extern crate std;
use std::io::Read;
use std::vec::Vec;

use crate::modes::Mode;
use crate::{Encoder, RgbPixel, Synthesizer};

/// A Robot 36 transmission generated by `PySSTV`
/// (`tests/scripts/encode_with_pysstv.py`); not committed.
pub const PYSSTV_FIXTURE: &str = "tests/assets/patch-robot36-pysstv.wav";
/// The real off-air Robot 36 recording captured by a ground station.
pub const GROUND_STATION_RECORDING: &str = "tests/assets/real_recording.wav.gz";
/// The image the ground-station recording and the `PySSTV` fixture carry.
#[cfg(feature = "image")]
pub const SOURCE_IMAGE: &str = "examples/patch.png";

/// An image at the mode's resolution, brightening to the right in red,
/// downwards in green and diagonally in blue.
pub fn gradient_image(mode: Mode) -> Vec<RgbPixel> {
    let (width, height) = mode.resolution();
    let pixel_at = |row: u32, column: u32| {
        RgbPixel::new(
            (column * 255 / width) as u8,
            (row * 255 / height) as u8,
            ((row + column) * 255 / (width + height)) as u8,
        )
    };
    (0..height)
        .flat_map(|row| (0..width).map(move |column| pixel_at(row, column)))
        .collect()
}

/// The samples of the image's whole transmission, header included.
pub fn transmit(mode: Mode, image: &[RgbPixel], sample_rate: u32) -> Vec<i16> {
    let encoder = Encoder::new(mode, image.iter().copied()).unwrap();
    Synthesizer::new(encoder, sample_rate).collect()
}

/// Mean absolute per-channel difference between two images of equal size.
pub fn mean_abs_error(expected: &[RgbPixel], actual: &[RgbPixel]) -> f64 {
    assert_eq!(expected.len(), actual.len());
    let difference = |a: u8, b: u8| f64::from(a.abs_diff(b));
    let total: f64 = expected
        .iter()
        .zip(actual)
        .map(|(e, a)| {
            difference(e.red(), a.red())
                + difference(e.green(), a.green())
                + difference(e.blue(), a.blue())
        })
        .sum();
    total / (expected.len() as f64 * 3.0)
}

/// The pixels of an image file.
#[cfg(feature = "image")]
pub fn read_image(path: &str) -> Vec<RgbPixel> {
    image::open(asset_path(path))
        .unwrap()
        .to_rgb8()
        .pixels()
        .map(|pixel| RgbPixel::new(pixel[0], pixel[1], pixel[2]))
        .collect()
}

/// Read one of the ISS recordings, fetching the set on first use as
/// `tests/iss_recordings.rs` does.
pub fn read_iss_recording(name: &str) -> (Vec<i16>, u32) {
    static FETCH: std::sync::Once = std::sync::Once::new();
    let path = std::format!("tests/assets/iss/{name}");
    FETCH.call_once(|| {
        if asset_path(&path).exists() {
            return;
        }
        let status = std::process::Command::new("python3")
            .arg(asset_path("tests/scripts/fetch_iss_recordings.py"))
            .current_dir(env!("CARGO_MANIFEST_DIR"))
            .status()
            .expect("run tests/scripts/fetch_iss_recordings.py");
        assert!(status.success(), "fetching the ISS recordings failed");
    });
    read_wav(&path)
}

/// Read a fixture generated by one of the `tests/scripts/` tools, or
/// `None` on machines (like CI) that have not generated it, as
/// `tests/interop.rs` does.
pub fn read_generated_wav(path: &str) -> Option<(Vec<i16>, u32)> {
    if asset_path(path).exists() {
        return Some(read_wav(path));
    }
    std::eprintln!("skipping: {path} not found, generate it with tests/scripts/");
    None
}

pub fn read_gzipped_wav(path: &str) -> (Vec<i16>, u32) {
    let mut wav = Vec::new();
    flate2::read::GzDecoder::new(open_asset(path))
        .read_to_end(&mut wav)
        .unwrap();
    wav_samples(&wav)
}

pub fn read_wav(path: &str) -> (Vec<i16>, u32) {
    let mut wav = Vec::new();
    open_asset(path).read_to_end(&mut wav).unwrap();
    wav_samples(&wav)
}

fn open_asset(path: &str) -> std::fs::File {
    std::fs::File::open(asset_path(path)).unwrap_or_else(|_| panic!("{path} not found"))
}

fn asset_path(path: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(path)
}

/// The first channel of a WAV, scaled to 16 bit, and its sample rate.
fn wav_samples(wav: &[u8]) -> (Vec<i16>, u32) {
    let reader = hound::WavReader::new(std::io::Cursor::new(wav)).unwrap();
    let spec = reader.spec();
    let channels = usize::from(spec.channels);
    let samples = match spec.sample_format {
        hound::SampleFormat::Int => reader
            .into_samples::<i32>()
            .step_by(channels)
            .map(|sample| (sample.unwrap() >> (spec.bits_per_sample - 16)) as i16)
            .collect(),
        hound::SampleFormat::Float => reader
            .into_samples::<f32>()
            .step_by(channels)
            .map(|sample| (sample.unwrap() * f32::from(i16::MAX)) as i16)
            .collect(),
    };
    (samples, spec.sample_rate)
}
