// Test helpers outside #[test] functions are not covered by the clippy.toml
// test allowances.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

//! Interoperability tests against references produced by external SSTV tools.
//!
//! Both need reference files generated into the (gitignored) `tests/assets/`
//! directory and skip with instructions if the reference is missing. Generate
//! them with:
//!
//! ```text
//! python3 tests/scripts/encode_with_pysstv.py   # decoder test input
//! python3 tests/scripts/decode_reference.py     # encoder test reference
//! ```
//!
//! See `tests/scripts/requirements.txt` for the Python setup.

mod common;
use common::{asset, generated_asset, mean_abs_error, read_audio, read_image, save_decoded};
use sstv::{Decoder, modes};

/// A Robot36 signal generated by `PySSTV`, for our decoder to decode.
const PYSSTV_FIXTURE: &str = "patch-robot36-pysstv.wav";
/// Our encoder's output as decoded by the independent `sstv` decoder.
const SSTV_REFERENCE: &str = "encoder-robot36-sstv.png";

/// Our decoder should reconstruct a PySSTV-generated Robot36 signal.
#[test]
fn decoder_matches_pysstv_reference() {
    let Some(fixture) = generated_asset(
        PYSSTV_FIXTURE,
        "python3 tests/scripts/encode_with_pysstv.py",
    ) else {
        return;
    };
    let (samples, sample_rate) = read_audio(&fixture);

    let decoded = Decoder::new(samples.into_iter(), sample_rate)
        .with_mode(modes::ROBOT_36)
        .decode()
        .expect("an image in the recording");
    save_decoded("pysstv", &decoded);

    let error = mean_abs_error(&read_image(&asset("patch.png")), decoded.pixels());
    // PySSTV uses different YUV coefficients, so some colour drift is expected,
    // and a real transmission may not carry the last line or two; a misaligned
    // decode would be far higher (40+).
    assert!(error < 15.0, "decode error {error} too high");
}

/// The independent `sstv` decoder should reconstruct our encoder's output,
/// validating the encoder against a foreign implementation.
#[test]
fn encoder_output_decodes_via_sstv() {
    let Some(reference) =
        generated_asset(SSTV_REFERENCE, "python3 tests/scripts/decode_reference.py")
    else {
        return;
    };

    let decoded = read_image(&reference);
    let original = read_image(&asset("patch.png"));
    assert_eq!(
        decoded.len(),
        original.len(),
        "decoded image dimensions differ from the source",
    );

    let error = mean_abs_error(&original, &decoded);
    // Foreign decoder → timing/colourspace interpretation differences. Measured
    // ~13.6; 20 leaves margin while still catching a broken encoder.
    assert!(
        error < 20.0,
        "encoder -> sstv decode error {error} too high"
    );
}
