//! Interoperability tests against references produced by external SSTV tools.
//!
//! Both require reference files in the (gitignored) `local/` directory and fail
//! with instructions if the reference is missing. Generate them with:
//!
//! ```text
//! python3 scripts/encode_with_pysstv.py   # decoder test input
//! python3 scripts/decode_reference.py     # encoder test reference
//! ```
//!
//! See `scripts/requirements.txt` for the Python setup.

use std::path::Path;

use sstv::{Event, RgbPixel, RowDecoder};

/// Robot36 resolution.
const WIDTH: usize = 320;
const HEIGHT: usize = 240;

/// A Robot36 signal generated by PySSTV, for our decoder to decode.
const PYSSTV_FIXTURE: &str = "tests/assets/patch-robot36-pysstv.wav";
/// Our encoder's output as decoded by the independent `sstv` decoder.
const SSTV_REFERENCE: &str = "tests/assets/encoder-robot36-sstv.png";
/// The source image both references derive from.
const SOURCE_IMAGE: &str = "examples/patch.png";

fn require(path: &str, generate_with: &str) {
    assert!(
        Path::new(path).exists(),
        "{path} not found. Generate it with `{generate_with}`",
    );
}

/// Load an image as raw row-major RGB bytes, with its dimensions.
fn image_bytes(path: &str) -> (Vec<u8>, (u32, u32)) {
    let image = image::open(path).expect("open image").to_rgb8();
    let dimensions = image.dimensions();
    (image.into_raw(), dimensions)
}

/// Flatten pixels to raw row-major RGB bytes.
fn pixels_to_bytes(pixels: &[RgbPixel]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(pixels.len() * 3);
    for pixel in pixels {
        bytes.extend_from_slice(&[pixel.red(), pixel.green(), pixel.blue()]);
    }
    bytes
}

/// Mean absolute per-channel error between two equal-length RGB byte buffers.
fn mean_abs_error(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len());
    let sum: u64 = a
        .iter()
        .zip(b)
        .map(|(x, y)| (*x as i32 - *y as i32).unsigned_abs() as u64)
        .sum();
    sum as f64 / a.len() as f64
}

/// Read a WAV, returning its samples (first channel) and sample rate.
fn read_wav(path: &str) -> (Vec<i16>, u32) {
    let reader = hound::WavReader::open(path).expect("open wav");
    let channels = reader.spec().channels as usize;
    let sample_rate = reader.spec().sample_rate;
    let samples = reader
        .into_samples::<i16>()
        .map(|sample| sample.expect("read sample"))
        .step_by(channels)
        .collect();
    (samples, sample_rate)
}

/// Our decoder should reconstruct a PySSTV-generated Robot36 signal.
#[test]
fn decoder_matches_pysstv_reference() {
    require(
        PYSSTV_FIXTURE,
        "python3 tests/scripts/encode_with_pysstv.py",
    );

    let (samples, sample_rate) = read_wav(PYSSTV_FIXTURE);

    // Reconstruct the first image in the stream from the decoder's events.
    let mut decoded: Vec<RgbPixel> = Vec::new();
    for event in RowDecoder::new(samples.into_iter(), sample_rate) {
        match event {
            Event::ImageStart(_) if !decoded.is_empty() => break,
            Event::ImageStart(_) => {}
            Event::Row(row) => decoded.extend_from_slice(row.pixels()),
            Event::ImageEnd { .. } => break,
        }
    }

    // A real transmission may not carry the last line or two to the very end.
    let rows = decoded.len() / WIDTH;
    assert!(rows >= HEIGHT - 2, "only decoded {rows} of {HEIGHT} rows");

    let decoded_bytes = pixels_to_bytes(&decoded);
    let (reference, _) = image_bytes(SOURCE_IMAGE);
    let error = mean_abs_error(&reference[..decoded_bytes.len()], &decoded_bytes);
    // PySSTV uses different YUV coefficients, so some colour drift is expected;
    // a misaligned decode would be far higher (40+).
    assert!(error < 15.0, "decode error {error} too high");
}

/// The independent `sstv` decoder should reconstruct our encoder's output,
/// validating the encoder against a foreign implementation.
#[test]
fn encoder_output_decodes_via_sstv() {
    require(SSTV_REFERENCE, "python3 tests/scripts/decode_reference.py");

    let (decoded, decoded_dimensions) = image_bytes(SSTV_REFERENCE);
    let (original, original_dimensions) = image_bytes(SOURCE_IMAGE);
    assert_eq!(
        decoded_dimensions, original_dimensions,
        "decoded image dimensions differ from the source",
    );

    let error = mean_abs_error(&original, &decoded);
    // Foreign decoder → timing/colourspace interpretation differences. Measured
    // ~13.6; 20 leaves margin while still catching a broken encoder.
    assert!(
        error < 20.0,
        "encoder -> sstv decode error {error} too high"
    );
}
