//! Helpers shared by the integration tests.

// Without some features, the tests that use a helper are not built.
#![allow(dead_code)]

use std::io::{Cursor, Read};
use std::panic::Location;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::Once;

use sstv::{DecodedImage, Mode, RgbPixel};

/// A test image at the mode's resolution with variation in all three channels.
pub fn test_image(mode: Mode) -> Vec<RgbPixel> {
    let (width, height) = mode.resolution();
    let mut pixels = Vec::with_capacity((width * height) as usize);
    for y in 0..height {
        for x in 0..width {
            let red = (x * 255 / (width - 1)) as u8;
            let green = (y * 255 / (height - 1)) as u8;
            let blue = ((x + y) * 255 / (width + height - 2)) as u8;
            pixels.push(RgbPixel::new(red, green, blue));
        }
    }
    pixels
}

/// Mean absolute per-channel error between two images of equal length.
pub fn mean_abs_error(a: &[RgbPixel], b: &[RgbPixel]) -> f64 {
    assert_eq!(a.len(), b.len());
    let total: u64 = a
        .iter()
        .zip(b)
        .map(|(p, q)| {
            let d = |x: u8, y: u8| u64::from((i32::from(x) - i32::from(y)).unsigned_abs());
            d(p.red(), q.red()) + d(p.green(), q.green()) + d(p.blue(), q.blue())
        })
        .sum();
    total as f64 / (a.len() as f64 * 3.0)
}

/// The path of a file in `tests/assets/`, fetching the assets with
/// `tests/scripts/fetch_assets.py` on first use. No asset is committed.
pub fn asset(name: &str) -> PathBuf {
    static FETCH: Once = Once::new();
    let path = repository().join("tests/assets").join(name);
    if !path.exists() {
        FETCH.call_once(|| {
            let script = repository().join("tests/scripts/fetch_assets.py");
            let status = Command::new("python3")
                .arg(&script)
                .status()
                .expect("run tests/scripts/fetch_assets.py");
            assert!(status.success(), "fetching the test assets failed");
        });
    }
    assert!(
        path.exists(),
        "{name} is missing after fetching the test assets"
    );
    path
}

/// The path of a fixture in `tests/assets/` generated by one of the
/// `tests/scripts/` tools, or `None` on machines (like CI) that have not
/// generated it, so the test can skip.
pub fn generated_asset(name: &str, generate_with: &str) -> Option<PathBuf> {
    let path = repository().join("tests/assets").join(name);
    if path.exists() {
        return Some(path);
    }
    eprintln!("skipping: {name} not found, generate it with `{generate_with}`");
    None
}

/// The first channel of an audio file, scaled to 16 bit, and its sample
/// rate. Reads WAV (also gzip-compressed), Ogg Vorbis and FLAC.
pub fn read_audio(path: &Path) -> (Vec<i16>, u32) {
    let bytes = std::fs::read(path).unwrap_or_else(|_| panic!("read {}", path.display()));
    match path.extension().and_then(|extension| extension.to_str()) {
        Some("gz") => wav_samples(&gunzip(&bytes)),
        Some("wav") => wav_samples(&bytes),
        Some("ogg") => ogg_samples(&bytes),
        Some("flac") => flac_samples(&bytes),
        _ => panic!("unknown audio format: {}", path.display()),
    }
}

/// The pixels of an image file, row by row.
pub fn read_image(path: &Path) -> Vec<RgbPixel> {
    image::open(path)
        .unwrap_or_else(|_| panic!("open {}", path.display()))
        .to_rgb8()
        .pixels()
        .map(|pixel| RgbPixel::new(pixel[0], pixel[1], pixel[2]))
        .collect()
}

/// Store an image this crate decoded for inspection, under
/// `target/tmp/decoded/<calling test file>/<name>.png`. Never committed.
#[track_caller]
pub fn save_decoded(name: &str, decoded: &DecodedImage) {
    let bytes = decoded
        .pixels()
        .iter()
        .flat_map(|pixel| [pixel.red(), pixel.green(), pixel.blue()])
        .collect();
    let buffer = image::RgbImage::from_raw(decoded.width() as u32, decoded.height() as u32, bytes)
        .expect("pixel count matches the dimensions");
    save_decoded_buffer(name, &buffer);
}

/// Like [`save_decoded`], for an image already converted to a buffer.
#[track_caller]
pub fn save_decoded_buffer(name: &str, buffer: &image::RgbImage) {
    let test_file = Path::new(Location::caller().file())
        .file_stem()
        .expect("the calling test file has a name");
    let directory = Path::new(env!("CARGO_TARGET_TMPDIR"))
        .join("decoded")
        .join(test_file);
    std::fs::create_dir_all(&directory).expect("create the decoded image directory");
    buffer
        .save(directory.join(format!("{name}.png")))
        .expect("save the decoded image");
}

fn repository() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn gunzip(bytes: &[u8]) -> Vec<u8> {
    let mut decompressed = Vec::new();
    flate2::read::GzDecoder::new(bytes)
        .read_to_end(&mut decompressed)
        .expect("gunzip");
    decompressed
}

fn wav_samples(bytes: &[u8]) -> (Vec<i16>, u32) {
    let reader = hound::WavReader::new(Cursor::new(bytes)).expect("parse wav");
    let spec = reader.spec();
    let channels = usize::from(spec.channels);
    let samples = match spec.sample_format {
        hound::SampleFormat::Int => reader
            .into_samples::<i32>()
            .step_by(channels)
            .map(|sample| (sample.expect("read sample") >> (spec.bits_per_sample - 16)) as i16)
            .collect(),
        hound::SampleFormat::Float => reader
            .into_samples::<f32>()
            .step_by(channels)
            .map(|sample| (sample.expect("read sample") * f32::from(i16::MAX)) as i16)
            .collect(),
    };
    (samples, spec.sample_rate)
}

fn ogg_samples(bytes: &[u8]) -> (Vec<i16>, u32) {
    let mut reader =
        lewton::inside_ogg::OggStreamReader::new(Cursor::new(bytes)).expect("parse ogg");
    let channels = usize::from(reader.ident_hdr.audio_channels);
    let mut samples = Vec::new();
    while let Some(packet) = reader.read_dec_packet_itl().expect("decode ogg") {
        samples.extend(packet.iter().step_by(channels));
    }
    (samples, reader.ident_hdr.audio_sample_rate)
}

fn flac_samples(bytes: &[u8]) -> (Vec<i16>, u32) {
    let mut reader = claxon::FlacReader::new(Cursor::new(bytes)).expect("parse flac");
    let info = reader.streaminfo();
    let shift = info.bits_per_sample.saturating_sub(16);
    let samples = reader
        .samples()
        .step_by(info.channels as usize)
        .map(|sample| (sample.expect("decode flac") >> shift) as i16)
        .collect();
    (samples, info.sample_rate)
}
