#!/usr/bin/env python3
"""Encode examples/patch.png into a Robot36 WAV using PySSTV.

Produces the fixture the decoder interop test reads: a WAV generated by an
independent SSTV implementation. Written into tests/assets/ (gitignored *.wav).

Regenerate with:  python3 tests/scripts/encode_with_pysstv.py
Requires:         pip install --no-deps -r tests/scripts/requirements.txt
"""

import os

from PIL import Image
from pysstv.color import Robot36

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INPUT = os.path.join(REPO_ROOT, "examples", "patch.png")
OUTPUT = os.path.join(REPO_ROOT, "tests", "assets", "patch-robot36-pysstv.wav")

# 48 kHz gives the decoder plenty of samples per cycle; 16-bit matches the
# encoder's PCM output.
SAMPLE_RATE = 48_000
BITS = 16


def main() -> None:
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)

    image = Image.open(INPUT).convert("RGB")
    image = image.resize((Robot36.WIDTH, Robot36.HEIGHT))

    Robot36(image, SAMPLE_RATE, BITS).write_wav(OUTPUT)
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
